### ISSUE TITLE
Prevent extra renders when rapidly receiving layout updates

### ISSUE THREAD

**Issue by hrigner** [qlik-oss/hamus.js#7]
useLayout - Add a render debouncer to delay triggering the render. Will improve performance and user experience.

**Comment by peol** [comment]
We should be careful about this, it might have unforseen behaviours (I think the current one we have in catwalk also relies on internal React APIs). Could we make this its own hook maybe (that uses `useLayout`?). Like `useDebouncedLayout`? :)

**Comment by hrigner** [comment]
I was planning a "normal" debouncer, not using the internal APIs, and making it optional with a bool in useLayout, sth like useLayout(model, useDebounce).

The useLayout func is not exactly the same as in catwalk, I'm not sure about whether to use debounce in modelChanged or in usePromise when calling the qix api.

**Comment by hrigner** [comment]
Closed with #15
